### ISSUE TITLE
Please clarify what this does in the README

### ISSUE THREAD

**Issue by cdeil** [duckdblabs/postgresscanner#6]
@hannes @Mytherin - Could you please explain with 2-3 sentences what postgresscanner does at the top of the README? I mean from a potential new user perspective, e.g. I'm looking for a PostgreSQL -> DuckDB sync tool and I wonder if this is relevant.

The README example for POSTGRES_ATTACH mentions SQLite. Is that correct or a typo? Does this have anything to do with SQLite?

Thanks!

**Comment by Mytherin** [comment]
I have added a short explanation and fixed the README:

> The postgresscanner extension allows DuckDB to directly read data from a running Postgres instance. The data can be queried directly from the underlying Postgres tables, or read into DuckDB tables.

Is that clear enough, or is there anything else you would add?

**Comment by cdeil** [comment]
Thanks!

So "postgresscanner" os for PostgreSQL -> DuckDB -> Client?

And "duckdb_fdw" is for DuckDB -> PostgreSQL -> Client?

https://github.com/alitrack/duckdb_fdw

Would be great if you could cross-link the two PostgreSQL / DuckDB integration options from the README and explain when to use which.

For me the README and what it does is now clearer. Although as a beginner with PostgreSQL extensions and DuckDB it's still difficult for me to judge if I should use it and how I would use it. The motivation to use this extension is performance? To try it out I could install this extension on the PostgreSQL as described in the README. But then to benefit I could e.g. create an in-memory or on-disk DuckDB locally and start querying? This would then be more performant that directly using psycopg or https://turbodbc.readthedocs.io/en/latest/ ?

You see, typical DuckDB user here that comes from the data science world and doesn't know much about databases. :-)

**Comment by Alex-Monahan** [comment]
Hello!

You can think of the PostgresScanner as DuckDB pulling from Postgres, whereas the FDW is Postgres pushing to DuckDB.

Yes, performance is one motivation, but being able to stay within DuckDB while still querying Postgres (so Python is optional) should also improve ease of use!

**Comment by cdeil** [comment]
Thanks for the explanations!
