### ISSUE TITLE
how to install？when I make then raise error

### ISSUE THREAD

**Issue by wonb168** [duckdblabs/postgresscanner#7]
`git clone https://gitee.com/wonb168/postgresscanner.git
cd postgresscanner
make`

(base) [root@ovf72-1511 install]# cd postgresscanner/
(base) [root@ovf72-1511 postgresscanner]# make
cd duckdb && \
BUILD_TPCDS=1 BUILD_TPCH=1 make release
make[1]: Entering directory `/root/install/postgresscanner/duckdb'
make[1]: *** No rule to make target `release'.  Stop.
make[1]: Leaving directory `/root/install/postgresscanner/duckdb'
make: *** [duckdb_release] Error 2
(base) [root@ovf72-1511 postgresscanner]#

**Comment by hemora** [comment]
Got the same problem, this worked for me:

1. Make sure you have installed cmake, flex, bison
2. Clone the main duckdb project contents inside the `postgresscanner/duckdb` folder 
3. Start fresh with `make clean`
4. Run `make` again

That will produce the executable `postgres_scanner.duckdb_extension` . Before loading it you should run duckdb with the  `-unsigned` flag

**Comment by wangxiaoying** [comment]
> `git clone https://gitee.com/wonb168/postgresscanner.git cd postgresscanner make`
> 
> (base) [root@ovf72-1511 install]# cd postgresscanner/ (base) [root@ovf72-1511 postgresscanner]# make cd duckdb && BUILD_TPCDS=1 BUILD_TPCH=1 make release make[1]: Entering directory `/root/install/postgresscanner/duckdb' make[1]: *** No rule to make target `release'. Stop. make[1]: Leaving directory `/root/install/postgresscanner/duckdb' make: *** [duckdb_release] Error 2 (base) [root@ovf72-1511 postgresscanner]#

I think you need to recursively fetch the submodule (duckdb) first. For the first time you can `git submodule update --init --recursive`

**Comment by hannes** [comment]
Please just use the INSTALL postgres_scanner with a recent DuckDB release.
